### ISSUE TITLE
Tool suggestion PHIST

### ISSUE THREAD

**Issue by papanikos** [MGXlab/phap#6]
Maybe interesting for integration...

Pre-print here: https://www.biorxiv.org/content/10.1101/2021.09.06.459169v1

Source code here: https://github.com/refresh-bio/phist

**Comment by dcarrillox** [comment]
Any thought on which database to use as `host_dir`?

**Comment by papanikos** [comment]
Ah, I missed that part. We can

1. Create a host_dir/ kmer_db whatever they need for a collection of genomes (e.g. RefSeq bacteria). 
  - This would require to maintain such a db though which I am not sure how well it is going to play out. 
  - In the paper they cite [Wang et al. 2020]( https://academic.oup.com/nargab/article/2/2/lqaa044/5861484) aka [VirHostMatcher-Net](https://github.com/WeiliWw/VirHostMatcher-Net) . They don't provide genome files but the models in `vhmnet/data/models` have GenBank accessions...

**Comment by dcarrillox** [comment]
For development, I create a database consisting on all the reference and representative bacterial and archaeal genomes from RefSeq (~15.5K genomes). In the docs it is described how to create the same database. In our system, it is with the rest of databases for the tools.
